name: check_template

on:
  workflow_call:
    inputs:
      integration_name:
        required: true
        type: string

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Print
        run: |
          echo "Input is ${{ inputs.integration_name }}"
      - name: Install
        run: |
          python -m pip install -U pip
          pip install --progress-bar off -U .[checking]
          pip install --progress-bar off -U .[test]

      - name: Install dependencies
        run: |
          if [ -f optuna_integration/${{ inputs.integration_name }}/requirements.txt ]; then
            pip install -r optuna_integration/${{ inputs.integration_name }}/requirements.txt
          fi

      - name: black
        run: |
          if [ -e optuna_integration/${{ inputs.integration_name }} ]; then
            black optuna_integration/${{ inputs.integration_name }} --check --diff
          fi
          if [ -e tests/${{ inputs.integration_name }} ]; then
            black tests/${{ inputs.integration_name }} --check --diff
          fi

      - name: isort
        run: |
          if [ -e optuna_integration/${{ inputs.integration_name }} ]; then
            isort optuna_integration/${{ inputs.integration_name }} --check --diff
          fi
          if [ -e tests/${{ inputs.integration_name }} ]; then
            isort tests/${{ inputs.integration_name }} --check --diff
          fi

      - name: mypy
        run: |
          if [ -e optuna_integration/${{ inputs.integration_name }} ]; then
            mypy optuna_integration/${{ inputs.integration_name }}
          fi
          if [ -e tests/${{ inputs.integration_name }} ]; then
            mypy tests/${{ inputs.integration_name }}
          fi

      - name: blackdoc
        run: |
          if [ -e optuna_integration/${{ inputs.integration_name }} ]; then
            blackdoc optuna_integration/${{ inputs.integration_name }} --check --diff
          fi
          if [ -e tests/${{ inputs.integration_name }} ]; then
            blackdoc tests/${{ inputs.integration_name }} --check --diff
          fi
