# Run tests and integration tests on Mac, which are triggered by each master push.
# Currently, Python3.8 is only used as an environment.
# This is mainly for the sake of speed.
name: mac-tests

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - '.github/workflows/mac-tests.yml'
  schedule:
    - cron: '0 23 * * SUN-THU'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/master' && github.run_number || github.ref }}
  cancel-in-progress: true

jobs:
  tests-mac:
    runs-on: macos-latest

    # Not intended for forks.
    if: github.repository == 'optuna/optuna-integration'
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Python3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Setup cache
      uses: actions/cache@v2
      env:
        cache-name: test
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-3.8-${{ env.cache-name }}-${{ hashFiles('**/setup.py') }}-v1
        restore-keys: |
          ${{ runner.os }}-3.8-${{ env.cache-name }}-${{ hashFiles('**/setup.py') }}

    - name: Setup mac environment
      run: |
        brew install libomp
        brew install open-mpi
        brew install openblas

    - name: Install
      run: |
        python -m pip install --upgrade pip

        # Install minimal dependencies and confirm that `import optuna` is successful.
        pip install --progress-bar off .
        pip install --progress-bar off .[test]
        pip install --progress-bar off .[integration]


    - name: Tests
      run: |
        pytest tests -m "integration"

      env:
        OMP_NUM_THREADS: 1
