name: Tests

on:
  push:
  pull_request: {}
  schedule:
    - cron: '0 23 * * SUN-THU'
  workflow_dispatch:

jobs:
  tests:
    if: (github.event_name == 'schedule' && github.repository == 'optuna/optuna-integration') || (github.event_name != 'schedule')
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Setup environment
      run: |
        sudo apt-get update
        sudo apt-get -y install libopenblas-dev
        curl -LsSf https://astral.sh/uv/install.sh | sh
        uv venv
        ls -la
        source ./.venv/bin/activate
        uv pip install optuna

    - name: Install
      run: |
        uv pip install --progress-bar off .[test]
        uv pip install --progress-bar off .[all]
        uv pip install distributed

    - name: Tests
      run: |
        uv pip install "numpy<1.24"
        pytest tests
